### ISSUE TITLE
Maybe move more technical text from Logobot wiki article to Logobot's own github?

### ISSUE THREAD

**Issue by q2dg** [swindonmakers/wiki#20]
I mean...now there are two "starting points" to get the point about Logobot project: this page (https://github.com/swindonmakers/snhack.github.io/wiki/LogoBot) and this page (https://github.com/swindonmakers/LogoBot) with different level of information detail. Although it's not dramatic, this fact is a little confusing for the newbie. Moreover, it's prone to inconsistencies (for instance, "principles/requirements" section in the former page isn't the same than "design principles" in the latter, as I understand it should be).

I propose move all technical stuff from the snhack.github.io's wiki to the swindonmakers/LogoBot github, leaving a simply explanation about the project in the former and putting all the rest in the latter. In fact, in the former i'd just put these pharagraphs:

```
 LogoBot is a simple, extensible, Arduino-based mobile robot developed by the Swindon Hackspace. It is heavily inspired by the vast number of existing mobile robots designs (Mirobot in particular). The development of the reference design has been kicked-off through the OpenSCAD Course and will be an ongoing collaborative project for all members of the Hackspace to participate in.

 See the LogoBot Documentation for detailed instructions on how to build a LogoBot (as well as the latest BOM)

 See the LogoBot Github for detailed discussion about the design principles, extension and customization ideas and other "tinkering" stuff.
```

And move the rest of the current content of snhack.github.io's wiki (Design section, Extension section, Customized section, etc.) to LogoBot github (wiki). I'd also remove BOM section from both places because it already is in guides.

**Comment by RobertCL** [comment]
Its taken a long time(!) but it's done.
